Nexitally Quantumult X
Updated: 2099-01-01
anytls=example.com:443, password=pwd, over-tls=true, tls-host=apple.com, udp-relay=true, tag=HK-01

[server_local]
anytls=example.net:443, password=pwd, over-tls=true, tls-host=apple.com, udp-relay=true, tag=JP-01
