[server_local]
anytls = osaka.example.invalid:443, password=example-password, tls-host=osaka.example.invalid, tag=JP-Osaka-01
anytls = info.example.invalid:443, password=example-password, tag=Traffic: 12 GB
anytls = info.example.invalid:443, password=example-password, tag=Expire: 2099-12-31
anytls = info.example.invalid:443, password=example-password, tag=Reset on the 1st
anytls = info.example.invalid:443, password=example-password, tag=Days Left: 12
anytls = info.example.invalid:443, password=example-password, tag=流量: 12 GB
anytls = info.example.invalid:443, password=example-password, tag=到期: 2099-12-31
anytls = info.example.invalid:443, password=example-password, tag=剩余: 12
anytls = info.example.invalid:443, password=example-password, tag=套餐: Premium
anytls = info.example.invalid:443, password=example-password, tag=[Premium] Slot
[filter_local]
geoip, cn, direct
