[server_local]
https=example.com:443, username=name, password=pwd, tag=HTTPS
http=example.com:80, username=name, password=pwd, udp-relay=false, tag=HTTP-01
socks=example.com:1080, username=name, password=pwd, tag=SOCKS
socks5=example.com:80, username=name, password=pwd, udp-relay=false, tag=SOCKS5-01
