[server_local]
anytls=example.com:443, password=pwd, over-tls=true, tls-host=apple.com, udp-relay=true, tag=HK-01
shadowsocks=example.com:80, method=chacha20, password=pwd, udp-relay=false, tag=SS-01
vmess=example.com:80, method=none, password=23ad6b10-8d1a-40f7-8ad0-e3e35cd32291, udp-relay=false, tag=VM-01
vless=example.com:443, method=none, password=23ad6b10-8d1a-40f7-8ad0-e3e35cd32291, obfs=over-tls, udp-relay=false, tag=VL-01
trojan=example.com:443, password=pwd, over-tls=true, tls-verification=true, udp-relay=false, tag=TR-01
http=example.com:80, username=name, password=pwd, udp-relay=false, tag=HTTP-01
socks5=example.com:80, username=name, password=pwd, udp-relay=false, tag=SOCKS5-01
