[server_local]
; anytls=example.com:443, password=pwd, over-tls=true, tls-host=apple.com, udp-relay=true, tag=HK-01

http=127.0.0.1:80, tag=Traffic: empty plan
anytls=example.com:443, password=pwd, over-tls=true, tag=US [Premium]
