[server_local]
shadowsocks=info.example.test:443, method=aes-128-gcm, password=pwd, tag=Traffic: 12.3/100GB
shadowsocks=info.example.test:443, method=aes-128-gcm, password=pwd, tag=Expire: 2099-12-31
shadowsocks=info.example.test:443, method=aes-128-gcm, password=pwd, tag=Reset: 5 Days Left
anytls=tokyo-a.nodes.example.test:443, password=pwd, over-tls=true, tls-host=apple.com, udp-relay=true, tag=JP-Tokyo-A
