[server_local]

  
; anytls=example.com:443, password=pwd, over-tls=true, tls-host=apple.com, udp-relay=true, tag=HK-01
# anytls=example.net:443, password=pwd, over-tls=true, tls-host=apple.com, udp-relay=true, tag=JP-01
// shadowsocks=example.com:80, method=chacha20, password=pwd, udp-relay=false, tag=SS-01
anytls=example.com:443, password=pwd, over-tls=true, tls-host=apple.com, udp-relay=true, tag=HK-01
   anytls=example.com:443, password=pwd, over-tls=true, tls-host=apple.com, udp-relay=true, tag=HK-01
anytls=example.net:443, password=pwd, over-tls=true, tls-host=apple.com, udp-relay=true, tag=JP-01
http=127.0.0.1:80, tag=Traffic leftover
