[server_local]
http=helper-a.nodes.example.test:8080, username=user, password=pwd, over-tls=false, tag=Helper-HTTP
https=https-helper.nodes.example.test:443, username=user, password=pwd, tag=HTTPS-Drop
http =helper-c.nodes.example.test:8080, username=user, password=pwd, tag=Helper-HTTP-Spaced
