[server_local]
http=127.0.0.1:80, tag=Traffic: 1 GB
http=127.0.0.1:80, tag=Expire: 2099-01-01
http=127.0.0.1:80, tag=Reset: tomorrow
http=127.0.0.1:80, tag=Days Left: 3
http=127.0.0.1:80, tag=剩余流量
http=127.0.0.1:80, tag=套餐到期
anytls=example.com:443, password=pwd, over-tls=true, tls-host=apple.com, udp-relay=true, tag=HK-01
