[server_local]
anytls=jp-01.example.com:443, password=pwd, over-tls=true, tls-host=www.apple.com, udp-relay=true, tag=Nexitally-JP-01
shadowsocks=info.example.com:80, method=chacha20, password=pwd, tag=Traffic: ignore-me

[policy]
static = Final, Nexitally-JP-01, direct
