# The section heading is case-insensitive.

[SERVER_LOCAL]
trojan=kr-01.example.com:443, password=pwd, over-tls=true, tls-host=www.example.net, tag=Nexitally-KR-01

[POLICY]
static = Final, Nexitally-KR-01, direct
