[server_local]
anytls=trap.example.test:443, password=TrafficJam, over-tls=true, tag=Trap
anytls=tokyo-a.nodes.example.test:443, password=pwd, over-tls=true, tls-host=apple.com, udp-relay=true, tag=JP-Tokyo-A
