[server_local]
; semicolon comment
# hash comment
// slash comment

anytls=keep-a.example.com:443, password=example-password, over-tls=true, tls-host=www.example.com, udp-relay=true, tag=Keep-A
anytls=keep-a.example.com:443, password=example-password, over-tls=true, tls-host=www.example.com, udp-relay=true, tag=Keep-A
anytls=keep-b.example.com:443, password=example-password, over-tls=true, tls-host=www.example.com, udp-relay=true, tag=Keep-B
anytls=keep-b.example.com:443, password=example-password, over-tls=true, tls-host=www.example.com, udp-relay=true, tag=Keep-B

[policy]
static = Proxy, Keep-A, Keep-B, direct
