  [server_local]  
; semicolon comment
# hash comment
// slash comment

  anytls=hk-01.nodes.example.invalid:443, password=pwd, over-tls=true, tls-host=www.apple.com, udp-relay=true, tag=Hong Kong 01  

anytls=jp-02.nodes.example.invalid:443, password=pwd, over-tls=true, tls-host=www.apple.com, udp-relay=true, tag=Tokyo 02

[policy]
static = CRLF, Hong Kong 01, Tokyo 02
