[general]
server_check_url = http://www.example.com/generate_204

[server_local]
anytls=bom-a.example.com:443, password=example-password, over-tls=true, tls-host=www.example.com, udp-relay=true, tag=BOM-A
anytls=bom-b.example.com:443, password=example-password, over-tls=true, tls-host=www.example.com, udp-relay=true, tag=BOM-B

[filter_local]
final, direct
