[server_local]
anytls=plain.example.com:443, password=example-password, over-tls=true, tls-host=www.example.com, udp-relay=true, tag=HK-01
anytls=traffic-name.example.com:443, password=example-password, over-tls=true, tls-host=www.example.com, udp-relay=true, tag=HK-Traffic-01
anytls=expire-name.example.com:443, password=example-password, over-tls=true, tls-host=www.example.com, udp-relay=true, tag=Expire-Notice
anytls=days-left.example.com:443, password=example-password, over-tls=true, tls-host=www.example.com, udp-relay=true, tag=Days Left Panel

[filter_local]
final, direct
