[general]
server_check_url = http://www.example.com/generate_204

    [server_local]
anytls=indented.example.com:443, password=example-password, over-tls=true, tls-host=www.example.com, udp-relay=true, tag=Indented-Header

[filter_local]
final, direct
