[server_local]
anytls=first.example.com:443, password=example-password, over-tls=true, tls-host=www.example.com, udp-relay=true, tag=FIRST-01

[filter_local]
final, direct

[server_local]
anytls=second.example.com:443, password=example-password, over-tls=true, tls-host=www.example.com, udp-relay=true, tag=SECOND-01
