[server_local]
# Traffic: 0.00 GB / 500.00 GB
# Expire: 2026-12-31
# Days Left: 106
anytls=notice.nodes.example.invalid:443, password=pwd, over-tls=true, tls-host=www.apple.com, udp-relay=true, tag=套餐 Traffic Expire
anytls=premium.nodes.example.invalid:443, password=pwd, over-tls=true, tls-host=www.apple.com, udp-relay=true, tag=Osaka [Premium]

[filter_local]
final, proxy
