[general]
server_check_url = http://www.gstatic.com/generate_204

[policy]
static = No-Servers-Here, direct

[server_remote]
https://example.com/other-resource, tag=Unrelated, enabled=false

[filter_local]
final, direct
