[server_local]
hysteria2=example.com:443, password=pwd, tag=HY2
tuic=example.com:443, password=pwd, tag=TUIC
wireguard=example.com:51820, tag=WG
https=example.com:443, username=name, password=pwd, tag=HTTPS
socks=example.com:1080, username=name, password=pwd, tag=SOCKS
anytls=example.com:443, password=pwd, over-tls=true, tls-host=apple.com, udp-relay=true, tag=HK-01
