[general]
server_check_url = http://www.apple.com/generate_204

  [server_local]
anytls=hk-01.example.invalid:443, password=pwd, over-tls=true, tls-host=apple.com, tag=HK-01
	anytls=sg-01.example.invalid:443, password=pwd, over-tls=true, tls-host=apple.com, tag=SG-01

[filter_local]
final, proxy
