; supported regex allows whitespace before "=".

[server_local]
anytls =hk-01.example.invalid:443, password=pwd, over-tls=true, tls-host=apple.com, tag=HK-01
shadowsocks  =example.com:80, method=chacha20, password=pwd, tag=US-01
vmess=example.com:80, method=none, password=23ad6b10-8d1a-40f7-8ad0-e3e35cd32291, tag=VM-01

[filter_local]
final, proxy
