[server_local]
host, example.com, proxy
host-suffix, googleapis.com, proxy
ip-cidr, 10.0.0.0/8, direct
anytls=example.com:443, password=pwd, over-tls=true, tls-host=apple.com, udp-relay=true, tag=HK-01
