[server_local]

; semicolon comment
# hash comment
// slash comment
; anytls = hidden.example.invalid:443, password=example-password, tag=Hidden
   
anytls = kyoto.example.invalid:443, password=example-password, tag=JP-Kyoto-01
