[general]
server_check_url = http://www.apple.com/generate_204

[policy]
static = Proxy, direct

[filter_local]
final, direct

[server_remote]
https://cdn.example.test/other.txt, tag=Other, enabled=false
